### ISSUE TITLE
Use composer properly

### ISSUE THREAD

**Issue by marco-c** [marco-c/wp-web-app-manifest-generator#8]
Stop using the `require_once(plugin_dir_path(__FILE__) . '../../marco-c/wp_serve_file/class-wp-serve-file.php');` hack.

See also https://github.com/mozilla/wp-sw-manager/pull/7/files#r58379952.

**Comment by staabm** [comment]
usually you would detect the "position" of yourself relative to the composer-root-project by something like that https://github.com/fruux/sabre-dav/blob/master/bin/sabredav.php#L30-L40

**Comment by marco-c** [comment]
Oh, thank you. It's still a little hacky, but better!

**Comment by staabm** [comment]
but as I see right now, you are not talking about re-using some binaries bundled with a package but of re-using classes of a different package.

this would be even easier by defining where your sources are and how to autoload them.
that way the composer autoloader will make sure your classes get autoloaded no matter where they are (you dont need manual require calls then)

**Comment by marco-c** [comment]
I will look into autoloading, it seems the best solution.

**Comment by staabm** [comment]
see https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by staabm** [comment]
feel free to CC me for PRs to progress on this problem

**Comment by marco-c** [comment]
I'll still need https://github.com/fruux/sabre-dav/blob/master/bin/sabredav.php#L30-L40 to include `autoload.php`, right?

**Comment by staabm** [comment]
no. in the root package you just do `require __DIR__ . '/vendor/autoload.php';` nothing more.

the dependency packages just "publish" their classes via the autoloading (via autoload key in composer.json). composer will take care to generate a autoloader add `composer install` resp.  `composer update` time.

**Comment by marco-c** [comment]
So, this package `wp-web-app-manifest-generator` uses `wp_serve_file`, should it always be the root package's responsibility to load `wp_serve_file` even if it doesn't use it?

For example, `wp-web-push` is using both, but `wp-add-to-homescreen` isn't.

**Comment by staabm** [comment]
its the root package responsibility to `require __DIR__ . '/vendor/autoload.php';`.

each package on its own has to define in its very own composer.json where the classes are located.
no package has to know it from other packages.
